version: '2'
services:
    rotamanager-app:
        image: rotamanager
        external_links:
            - rotamanager-mysql:mysql
            - rotamanager-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rotamanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    rotamanager-mysql:
        extends:
            file: mysql.yml
            service: rotamanager-mysql
    rotamanager-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rotamanager-elasticsearch
